# Generated by Glenn Jocher (glenn.jocher@ultralytics.com) for https://github.com/ultralytics

import argparse
import os
import time

from flickrapi import FlickrAPI

from utils.general import download_uri

key = '3a41e17fdf30303487bb827caadf9ad3'  # Flickr API key https://www.flickr.com/services/apps/create/apply
secret = '82ce0c92d3ac3c39'


def get_urls(search='bulldozers', n=10, download=False):
    t = time.time()
    flickr = FlickrAPI(key, secret)
    license = ()  # https://www.flickr.com/services/api/explore/?method=flickr.photos.licenses.getInfo
    photos = flickr.walk(text=search,  # http://www.flickr.com/services/api/flickr.photos.search.html
                         extras='url_o',
                         per_page=500,  # 1-500
                         license=license,
                         sort='relevance')

    if download:
        dir = os.getcwd() + os.sep + 'images' + os.sep + search.replace(' ', '_') + os.sep  # save directory
        if not os.path.exists(dir):
            os.makedirs(dir)

    urls = []
    for i, photo in enumerate(photos):
        if i < n:
            try:
                # construct url https://www.flickr.com/services/api/misc.urls.html
                url = photo.get('url_o')  # original size
                if url is None:
                    url = f"https://farm{photo.get('farm')}.staticflickr.com/{photo.get('server')}/{photo.get('id')}_{photo.get('secret')}_b.jpg"


                # download
                if download:
                    download_uri(url, dir)

                # urls.append(url)
                print('%g/%g %s' % (i+1, n, url))
            except:
                print('%g/%g error...' % (i, n))
    print("Done! Please check the images folder.")
    exit()
    # import pandas as pd
    # urls = pd.Series(urls)
    # urls.to_csv(search + "_urls.csv")
    # print('Done. (%.1fs)' % (time.time() - t) + ('\nAll images saved to %s' % dir if download else ''))


if __name__ == '__main__':

    print("Flickr Web Crawler")
    print("Note: Flickr limits API calls to 3600 per hour. If you exceed this limit, the API key will be blocked for 24 hours.")
    keyword = input("Enter query string: ")
    number = input("Number of images: ")
    print("Ok, please wait...")
    
    # parser = argparse.ArgumentParser()
    # parser.add_argument('--search', type=str, default='honeybees on flowers', help='flickr search term')
    # parser.add_argument('--n', type=int, default=1, help='number of images')
    # parser.add_argument('--download', action='store_true', help='download images')
    # opt = parser.parse_args()

    # Check key
    help_url = 'https://www.flickr.com/services/apps/create/apply'
    assert key and secret, f'Flickr API key required in flickr_scraper.py L11-12. To apply visit {help_url}'

    get_urls(search=keyword,  # search term
             n=int(number),  # max number of images
             download=True)  # download images


             
